### ISSUE TITLE
FFDHE supported sizes

### ISSUE THREAD

**Issue by cbartle891** [tlswg/draft-deprecate-obsolete-kex#2]
> In practice, operators use 1024 bit FFDHE groups, since this is the maximum size that is widely supported. 

Do you mean the **minimum** size that is widely supported?

**Comment by nimia** [comment]
No, the maximum size.
To my knowledge, everyone understands that 1024-bit FFDHE leaves a small security margin, and were it possible, most people would want to use 2048-bit moduli. The problem is that some Java TLS stacks abort the connection when encountering moduli longer than 1024 bits. Since there is no mechanism to negotiate the group size, servers either use 1024-bit groups, or lose interoperability with these Java stacks. Server operators who choose to support FFDHE always go with the former option, to my knowledge. I'll try to find and cite an authoritative source for this.

**Comment by cbartle891** [comment]
Ahh, gotcha, thanks.
